- README.md
🔥[VQ4DiT] VQ4DiT: Efficient Post-Training Vector Quantization for Diffusion Transformers
> 🔥[VQ4DiT] VQ4DiT: Efficient Post-Training Vector Quantization for Diffusion Transformers

- README.md
🔥[LBQ] Low-Bitwidth Floating Point Quantization for Efficient High-Quality Diffusion Models
> 🔥[LBQ] Low-Bitwidth Floating Point Quantization for Efficient High-Quality Diffusion Models

- README.md
🔥[EE-Diffusion] A Simple Early Exiting Framework for Accelerated Sampling in Diffusion Models
> 🔥[EE-Diffusion] A Simple Early Exiting Framework for Accelerated Sampling in Diffusion Models

- README.md
🔥[TFM-PTQ] Temporal Feature Matters: A Framework for Diffusion Model Quantization
> 🔥[TFM-PTQ] Temporal Feature Matters: A Framework for Diffusion Model Quantization

- README.md
🔥[Diffusion-RWKV] Diffusion-RWKV: Scaling RWKV-Like Architectures for Diffusion Models
> 🔥[Diffusion-RWKV] Diffusion-RWKV: Scaling RWKV-Like Architectures for Diffusion Models

- README.md
🔥[DC-Solver] DC-Solver: Improving Predictor-Corrector Diffusion Sampler via Dynamic Compensation
> 🔥[DC-Solver] DC-Solver: Improving Predictor-Corrector Diffusion Sampler via Dynamic Compensation

- README.md
🔥🔥[AdaCache] Adaptive Caching for Faster Video Generation with Diffusion Transformers
> 🔥🔥[AdaCache] Adaptive Caching for Faster Video Generation with Diffusion Transformers

- README.md
🔥🔥[TeaCache] Timestep Embedding Tells: It’s Time to Cache for Video Diffusion Model
> 🔥🔥[TeaCache] Timestep Embedding Tells: It’s Time to Cache for Video Diffusion Model

- README.md
🔥🔥[LazyDiT] LazyDiT: Lazy Learning for the Acceleration of Diffusion Transformers
> 🔥🔥[LazyDiT] LazyDiT: Lazy Learning for the Acceleration of Diffusion Transformers

- README.md
…ith Causal Generation and Cache Sharing
> 🔥🔥[Ca2-VDM] Ca2-VDM: Efficient Autoregressive Video Diffusion Model with Causal Generation and Cache Sharing

- README.md
…ique for Diffusion Transformers
> 🔥🔥[SmoothCache] SmoothCache: A Universal Inference Acceleration Technique for Diffusion Transformers

- README.md
🔥🔥[FasterCache] FASTERCACHE: TRAINING-FREE VIDEO DIFFUSION MODEL ACCELERATION WITH HIGH QUALITY
> 🔥🔥[FasterCache] FASTERCACHE: TRAINING-FREE VIDEO DIFFUSION MODEL ACCELERATION WITH HIGH QUALITY

- README.md
🔥🔥[ToCa] ToCa: Accelerating Diffusion Transformers with Token-wise Feature Caching
> 🔥🔥[ToCa] ToCa: Accelerating Diffusion Transformers with Token-wise Feature Caching

- README.md
🔥🔥[SkipCache] Accelerating Vision Diffusion Transformers with Skip Branches
> 🔥🔥[SkipCache] Accelerating Vision Diffusion Transformers with Skip Branches

- README.md
🔥🔥[FBCache] Fastest HunyuanVideo Inference with Context Parallelism and First Block Cache on NVIDIA L20 GPUs
> 🔥🔥[FBCache] Fastest HunyuanVideo Inference with Context Parallelism and First Block Cache on NVIDIA L20 GPUs

- README.md
🔥[AB-Cache] AB-Cache: Training-Free Acceleration of Diffusion Models via Adams-Bashforth Cached Feature Reuse
> 🔥[AB-Cache] AB-Cache: Training-Free Acceleration of Diffusion Models via Adams-Bashforth Cached Feature Reuse

- README.md
🔥[DiTFastAttnV2] Head-wise Attention Compression for Multi-Modality Diffusion Transformers
> 🔥[DiTFastAttnV2] Head-wise Attention Compression for Multi-Modality Diffusion Transformers

- README.md
Great thanks for your efforts in consolidating resources and creating such an awesome project. Regarding diffusion quantization, I have added two of our works, which analyze the mixed bit-width of diffusion models and provide a framework analysis of DiT's quantization errors, along with practical CUDA kernel implementations. I have submitted a PR and hope it can be included.
> add quantization paper mixdq & viditq

- README.md
… Increment-Calibrated Caching with Channel-Aware Singular Value Decomposition
> 🔥🔥[Increment-Calibrated Cache] Accelerating Diffusion Transformer via Increment-Calibrated Caching with Channel-Aware Singular Value Decomposition

- README.md
SageAttention3: Microscaling FP4 Attention for Inference and An Exploration of 8-bit Training
> SageAttention3: Microscaling FP4 Attention for Inference and An Exploration of 8-bit Training

- README.md
> DraftAttention: Fast Video Diffusion via Low-Resolution Attention Guidance
